### ISSUE TITLE
cat-catch 显示异常

### ISSUE THREAD

**Issue by 775405984** [xifangczy/cat-catch#181]
**bug描述**
浏览器添加了--force-device-scale-factor=1.25 启动命令行

变成现在的样子

![image](https://github.com/xifangczy/cat-catch/assets/7196377/61fbcb28-3f8c-455d-a930-077bacb262e0)

点击捕获/录制
![image](https://github.com/xifangczy/cat-catch/assets/7196377/700330fd-570a-4e6d-96cf-33b575d1eb8e)

**扩展**
 - 2.4.0

**浏览器**
 - chromium 内核

**涉及网址**
非网址问题

**Comment by xifangczy** [comment]
在 设置 自定义CSS
写入
```css
body{ width : 700px; }
.more { bottom: 60px; z-index: 9999;}
```
临时解决这个问题
